# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import ctypes

from PyQt5.QtWidgets import QStatusBar
from PyQt5 import QtCore, QtGui, QtWidgets

from deskPage.toolSoft.enum_key import iconEnum


class Ui_MainWindow:

    def __init__(self):
        self.q = QtWidgets.QMainWindow()
        self.setupUi(MainWindow=self.q)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(303, 365)
        MainWindow.setMinimumSize(QtCore.QSize(303, 365))
        MainWindow.setMaximumSize(QtCore.QSize(303, 365))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 286, 171))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 61))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 14, 241, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.get_windows_list_button = QtWidgets.QPushButton(self.layoutWidget)
        self.get_windows_list_button.setObjectName("get_windows_list_button")
        self.horizontalLayout_2.addWidget(self.get_windows_list_button)
        self.test_windows_button = QtWidgets.QPushButton(self.layoutWidget)
        self.test_windows_button.setObjectName("test_windows_button")
        self.horizontalLayout_2.addWidget(self.test_windows_button)
        self.execute_dance_button = QtWidgets.QPushButton(self.layoutWidget)
        self.execute_dance_button.setObjectName("execute_dance_button")
        self.horizontalLayout_2.addWidget(self.execute_dance_button)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 261, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_1_windows = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_1_windows.setGeometry(QtCore.QRect(30, 20, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_1_windows.setFont(font)
        self.checkBox_1_windows.setObjectName("checkBox_1_windows")
        self.checkBox_2_windows = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2_windows.setGeometry(QtCore.QRect(103, 20, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_2_windows.setFont(font)
        self.checkBox_2_windows.setObjectName("checkBox_2_windows")
        self.checkBox_3_windows = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3_windows.setGeometry(QtCore.QRect(174, 20, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.checkBox_3_windows.setFont(font)
        self.checkBox_3_windows.setObjectName("checkBox_3_windows")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 261, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.check_intelnet_button = QtWidgets.QPushButton(self.groupBox_3)
        self.check_intelnet_button.setGeometry(QtCore.QRect(40, 50, 81, 31))
        self.check_intelnet_button.setObjectName("check_intelnet_button")
        self.execute_siginIn_button = QtWidgets.QPushButton(self.groupBox_3)
        self.execute_siginIn_button.setGeometry(QtCore.QRect(140, 50, 71, 31))
        self.execute_siginIn_button.setObjectName("execute_siginIn_button")
        self.tabWidget.addTab(self.tab_2, "")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(65, 190, 224, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.log_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_textBrowser.setGeometry(QtCore.QRect(10, 220, 284, 121))
        self.log_textBrowser.setObjectName("log_textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 186, 51, 25))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 303, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar()
        self.q.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "瓜牛劲舞团小助手"))
        self.groupBox.setTitle(_translate("MainWindow", "执行操作"))
        self.get_windows_list_button.setText(_translate("MainWindow", "获取窗口"))
        self.test_windows_button.setText(_translate("MainWindow", "检测窗口"))
        self.test_windows_button.setEnabled(False)
        self.execute_dance_button.setText(_translate("MainWindow", "开始执行"))
        self.execute_dance_button.setEnabled(False)
        self.groupBox_2.setTitle(_translate("MainWindow", "选择窗口"))
        self.checkBox_1_windows.setText(_translate("MainWindow", "窗口1"))
        self.checkBox_2_windows.setText(_translate("MainWindow", "窗口2"))
        self.checkBox_3_windows.setText(_translate("MainWindow", "窗口3"))
        self.checkBox_1_windows.setEnabled(False)
        self.checkBox_2_windows.setEnabled(False)
        self.checkBox_3_windows.setEnabled(False)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "团练/授业"))
        self.groupBox_3.setTitle(_translate("MainWindow", "执行操作"))
        self.check_intelnet_button.setText(_translate("MainWindow", "检测环境"))
        self.execute_siginIn_button.setText(_translate("MainWindow", "执行操作"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "微信签到"))
        self.label.setText(_translate("MainWindow", "日志打印"))

        ico_path = iconEnum.logo.value
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(ico_path), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.log_textBrowser.insertPlainText("  本程序仅供学习使用，请勿作为商业行为使用。\n"
                                             "  该版本使用大图找小图模式，理论上支持所有分辨率。\n"
                                             "  但尽量在1366*768以上分辨率使用。")

        # self.check_intelnet_button.setEnabled(False)
        # self.execute_siginIn_button.setEnabled(False)